styleguidist/react-docgen-typescript

- examples/react-styleguidist-example/components/ConstExport.tsx
- examples/react-styleguidist-example/components/PureRow.tsx
- src/__tests__/docgenConverter.spec.ts
- src/docgenConverter.ts
Missed to add `PureComponent` on docgenConverter.
Currently is not able to generate documentation with components that is extending from `PureComponent`
> Added PureComponent do docgenConverter and examples

- package.json
- src/__tests__/data/ColumnHigherOrderComponent.tsx
- src/__tests__/data/ColumnHigherOrderComponentHoc.tsx
- src/__tests__/data/transformAST.tsx
- src/__tests__/data/transformAST_hoc.ts
- src/__tests__/getFileDocumentation.spec.ts
- src/__tests__/transformAST.spec.ts
- src/getFileDocumentation.ts
- src/transformAST.ts
- yarn.lock
This is another attempt to make a fix for the issue #5
> HOC not working for external functions

- src/transformAST.ts
Currently this component:
```js
import * as React from 'react';
export interface IAppMenuProps {
/** Menu items */
menu: any;
}
export interface IAppMenuState {
menu: any;
}
/**
* App Menu Component
* 
* Renders a menu in horizontal mode
*/
export class AppMenu extends React.Component<IAppMenuProps, IAppMenuState> {
constructor(props, context) {
super(props, context);
this.state = {
menu: this.props.menu
};
this.handleClick  = this.handleClick.bind(this);
}
componentWillReceiveProps(newProps: IAppMenuProps) {
}
handleClick( info ) {
}
render() {
return (
<div onClick={this.handleClick}>
test
</div>
);
};
}
```
Returns a `cannot getText() of undefined` 
Methods have two `name: undefined` objects at the beginning and at the end
> Check if method name is not undefined

- src/__tests__/data/ExternalPropsComponent.tsx
- src/__tests__/data/ExternalPropsComponentProps.ts
- src/__tests__/data/transformAST.tsx
- src/__tests__/data/transformAST_external.ts
- src/__tests__/getFileDocumentation.spec.ts
- src/__tests__/transformAST.spec.ts
- src/printUtils.ts
- src/transformAST.ts
- the info about types from different files should be included as well
- this should fix #16
> Props defined in different file are recognised correctly

- src/__tests__/data/InlineConst.tsx
- src/__tests__/data/UnassignedLet.tsx
- src/__tests__/getFileDocumentation.spec.ts
- src/transformAST.ts
helps checks when using:
```javascript
class MyComponent extends React.Component<{}, {}> {
const myFunc = props => console.log('test');
}
```
By checking type and initializer
> Checked props to avoid getText() and kind issues

- package.json
- src/__tests__/docgenConverter.spec.ts
- src/docgenConverter.ts
- src/propTypesParser.ts
This should be fix for one part of the issue #27
> If there are no component found the default is returned from parse

- src/__tests__/data/transformAST.tsx
- src/__tests__/data/transformAST_external.ts
- src/__tests__/getFileDocumentation.spec.ts
- src/__tests__/transformAST.spec.ts
- src/printUtils.ts
- src/transformAST.ts
The TypeScript compiler splits JsDoc comments into two, and react-docgen-typescript was only pulling comment data from one of the two places.  This PR rebuilds the full comment from both parts.
(Pulling the comment formation logic out into a helper method also has the effect of providing  consistent handling both for null/undefined symbols when extracting comments and for whitespace-trimming.)
> Add support for JsDoc tags (fix issue #28)

- src/__tests__/data/ComponentWithDefaultProps.tsx
- src/__tests__/data/StatelessWithDefaultProps.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
fixes #37 
i've extended the parser to get default values from `Component.defaultProps` or JSDoc (`@default`)
i've also added two tests for class & stateless components, let me know if there are any other cases I should get.
here's a screenshot from one of my projects with a, rather exhaustive and contrived, default value list:
> support default props via defaultProps or JSDoc

- package.json
- src/__tests__/data/ColumnWithDefaultAnonymousExportOnly.tsx
- src/__tests__/data/ColumnWithDefaultExport.tsx
- src/__tests__/data/ColumnWithDefaultExportOnly.tsx
- src/__tests__/data/ColumnWithHtmlAttributes.tsx
- src/__tests__/data/ColumnWithPick.tsx
- src/__tests__/data/ConstExport.tsx
- src/__tests__/data/FlippableImage.tsx
- src/__tests__/data/PureRow.tsx
- src/__tests__/data/Regression_v0_0_12.tsx
- src/__tests__/data/Stateless.tsx
- src/__tests__/data/StatelessWithDefaultProps.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
> Adding support for default exports

- src/__tests__/buildFilter.ts
- src/__tests__/data/ColumnWithAnnotatedChildren.tsx
- src/__tests__/data/ColumnWithUndocumentedProps.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/buildFilter.ts
- src/index.ts
- src/parser.ts
- src/propTypesParser.ts
In case the "children" property has not been documented by the user the property should be ignored when creating the documentation.
But the property should be respected in case the user has specifically documented the "children" property.
I've introduced a config object that can be used to change the default behaviour by setting `ignoreChildrenIfNoDocAvailable = true`, which will then ignore any children properties that are not documented.
To configure the parser accordingly the following snippet can be used:
```javascript
propsParser: require('react-docgen-typescript')
.withCustomConfig('./tsconfig.json', {ignoreChildrenIfNoDocAvailable: true})
.parse
```
> Filter properties by static or dynamic conditions

- src/__tests__/data/tsconfig.json
- src/__tests__/parser.ts
- src/parser.ts
Currently the default tsconfig.json from `tsc --init` includes various comment styles. Those are allowed by Typescript because they use their own json parser. However those configs throw with `withCustomConfig` because of the usage of the native `JSON.parse`.
This pull requests fixes this behavior by using the same function to parse tsconfig that Typescript uses.
> Patch parse tsconfig

- package.json
- src/__tests__/data/ReactSFCAsConst.tsx
- src/__tests__/data/ReactSFCAsConstAsDefaultExport.tsx
- src/__tests__/data/ReactSFCAsConstAsNamedExport.tsx
- src/__tests__/parser.ts
- src/parser.ts
Closes #74 
I also have a `prepublishOnly` change in here -- I can remove it if you want, but it's a little better for other contributors (don't need `tsc` installed globally, and also no potential version mismatch)
Also noticed that this doesn't compile with TS2.7, so the typescript@^2.6.2 doesn't work with a fresh install
> Fix React.SFC-typed functional components

- src/__tests__/parser.ts
- src/parser.ts
The current implementation of `extractPropsFromTypeIfStatelessComponent()` in `src/parser.ts` works only with classes and lacks support for stateless components.
Paradoxically, there is a test located at `src/__tests__/parser.ts`, named 'should parse react stateless component with default props', which always returns true and does not actually check the default value (although 'hello' is expected and 'test' is returned, that test always passes).
This PR adds support for extracting default props from stateless components, and fixes the above test.
> Extracts default props from stateless components

- src/__tests__/data/StatelessWithReferencedDefaultProps.tsx
- src/__tests__/parser.ts
- src/parser.ts
Hi!
Pull Request #80 added support for referenced default props. This only worked in components declared with `class`, not as `StatelessComponent`.
Based on #80, I improved the tests for default prop parsing for stateless components, and prevented the error `TypeError: Cannot read property 'reduce' of undefined` by checking if `properties` is defined before calling `getPropMap`. This turned out to be enough to fix the issue.
Please let me know what you think, and thank you for your work so far!
> Add Support for Referenced Default Props in Stateless Components

- src/__tests__/data/StatefulDisplayNameDefaultExport.tsx
- src/__tests__/data/StatefulDisplayNameFolder/index.tsx
- src/__tests__/data/StatefulDisplayNameHOC.tsx
- src/__tests__/data/StatelessDisplayNameDefaultExport.tsx
- src/__tests__/data/StatelessDisplayNameFolder/index.tsx
- src/__tests__/data/StatelessDisplayNameHOC.tsx
- src/__tests__/parser.ts
- src/parser.ts
All of our components use the "ComponentName/index.tsx", which doesn't work most of the time, as we randomly get "index" as our name. This change uses the parent folder name when available.
I also added more tests for patterns we use, but they don't break here, but do break in our SG. So looking into it more.
> Use folder name as display name if file name is "index"

- package-lock.json
- src/__tests__/parser.ts
- src/parser.ts
The current implementation is limited to parsing one source file at a time, while `ts.createProgram` accepts multiple sourceFile paths.
I have a use case where all files that need parsing are known before calling `.parse`, so being able to pass them in one would be a nice improvement.
> Accept array of source file paths

- package.json
- src/parser.ts
As I checked the code for new version typescript in the parser.ts `symbol.getDocumentationComment()` method need typechecker parameter. Actually I fixed it and changed as `symbol.getDocumentationComment(this.checker)`.  Also it will not be problem for old version. I tested the example and it worked properly.
Fixed #96.
> * upgraded typescript version and fixed parsing comment problem.

- src/index.ts
Added a few additional exports to the module's index to support use with
react-docgen-typescript-loader. This allows this package to more easily
be used as a peer dependency.
Hello, and thank you for this project. I currently wrap this project in my project `react-docgen-typescript-loader`. I would like to be able to rely on this project as a peer dependency and need some additional exports from your library.
> Add additional exports to module entry point

- src/__tests__/buildFilter.ts
- src/__tests__/parser.ts
- src/parser.ts
This PR adds the ability to filter props based on where they were declared.
Solves: https://github.com/styleguidist/react-docgen-typescript/issues/56#issuecomment-400928419, https://github.com/styleguidist/react-docgen-typescript/issues/49#issuecomment-410401555
Currently we have no way of filtering props based on where they were declared. The common problem is props that extend `HTMLAttributes<T>` interface, e.g.:
```
import * as React from 'react';
export interface IButtonProps extends React.HTMLAttributes<HTMLButtonElement> {
size: 'large' | 'medium' | 'small';
}
```
Filtering them using `skipPropsWithoutDoc` is not enough as some aria attributes have documentation and forces the users to write documentation for props. Using `skipPropsWithName` can cause problems if names of props are …
> Allow filtering by parent interface or type declaration

- src/__tests__/parser.ts
- src/parser.ts
Thank you for maintaining this package. It's finding use in more and more places.
This change allows the parser to accept an existing instance of `ts.Program`. This is useful to allow outside libraries to implement language service integration or caching for performance improvements.
I'm not sure of the test is a bit overdone for something like this. Let me know if any changes are needed.
> Accept an existing TypeScript program instance

- README.md
- src/__tests__/data/StatelessDisplayNameStyledComponent.tsx
- src/__tests__/parser.ts
- src/parser.ts
This PR adds `componentNameResolver` and `getDefaultExportForFile` helpers for writing custom component name resolvers (important for styled components and such).
> General API for overriding component names

- src/index.ts
Forgot to do this earlier. Now the helper is exposed correctly.
> fix: Expose getDefaultExportForFile

- src/__tests__/data/StatelessWithDefaultProps.tsx
- src/__tests__/data/StatelessWithReferencedDefaultProps.tsx
- src/__tests__/data/StatelessWithSpreadDefaultProps.tsx
- src/__tests__/parser.ts
- src/parser.ts
**Fixes #86.**
When setting a default value for a prop with type `enum`, `defaultValue` was being returned as `null`. Upon further investigation the switch statement in `parser.getLiteralValueFromPropertyAssignment` was not handling the case where the prop type was an `enum`.
Before:
After:
> fix(parser): Fix enum default values #86

- package-lock.json
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
Resolves Issue #132 - Absolute file paths ruin our git diffs
List of changes:
- Parent filename is scanned for current directory name and trimmed to paths following that (inclusive)
- If the current directory name is never found we fallback to the full path (can assume that the path starts below current directory or in a different structure altogether)
- Added a parser test - `it should determine the parent fileName relative to the project directory`
- Added a `parent.fileName` comparison to `checkComponent`
> Determine parent fileNames relative to the current directory

- src/parser.ts
Allow extraction of component name and description even when no props are present
> Expose name and description from component even when no props are found

- src/__tests__/parser.ts
- src/parser.ts
Right now it is not possible use `react-docgen-typescript` when filenames are not legal js identifiers. This pull request fixes that.
> Fix filename to js identifier conversion

- src/parser.ts
Ran into the falling issue when trying to build Storybook with the types documentation.
Adding an additional check to first see if `name` is defined kept the build from failing.
> Add check to getTextValueOfFunctionProperty.

- src/__tests__/data/ColumnWithMethods.tsx
- src/__tests__/parser.ts
- src/parser.ts
#145 did not include the type information for method params, and does reflect optional params with a question mark `?`.
**BEFORE** Styleguidist renders only the parameter names, not their types:
```  public focusCell(rowIdx: number, colIdx?: number): void {```
**AFTER** Styleguidist renders the type names correctly:
I Don't Know What I'm Doing wrt Stylguidist, really, so if there's anything else I need to update, version number that needs to be bumped, etc. etc.
> Include param type information when parsing method params

- package-lock.json
- package.json
- src/__tests__/data/StatelessWithDestructuredProps.tsx
- src/__tests__/data/StatelessWithDestructuredPropsArrow.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
Fixes https://github.com/styleguidist/react-docgen-typescript/issues/154
Added support for extracting default prop values from object desctructuring inside functional components.
> feat: extract default props from destructuring

- README.md
- package-lock.json
- package.json
- src/__tests__/data/ExtractLiteralValuesFromEnum.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
Added option to convert typescript enums to unions of their values.
See [corresponding test](https://github.com/styleguidist/react-docgen-typescript/pull/201/files#diff-c4e2044ddda57c0b9b40f972fc77d27eR769) for example of usage and resulting docgen.
**Reason for adding this option:**
We are using react-docgen-typescript with Storybook to generate docgen info about components. And then we are using addon-smart-knobs to generate knobs automatically based on generated docgen. Currently we are able to generate select knobs automatically for string unions but to generate selects for enums we need to convert them to their actual string values.
> feat: extract literal values from enums

- src/__tests__/data/StatelessWithDefaultPropsAsString.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
Hi! I added a flag to parser can return default value not only as string type. I don't know, maybe flag is overhead and I can do this case is a default?
> feat: added flag to return default value not only as string type

- src/parser.ts
in cases where the name is `undefined` build will fail.
> fix: name variable  check to avoid build fail

- .github/workflows/nodejs.yml
- src/parser.ts
The current unit tests show that the parent.fileName test fails in windows.
This is because the code currently assumes the returned fileName from `getSourceFile` is a path separated based on OS separator, but in fact it is always '/' separated regardless if it is in Windows or Unix.
You can refer to this [GitHub Actions Log](https://github.com/malcolm-kee/react-docgen-typescript/pull/1/checks?check_run_id=271997510#step:5:58).
Note: I added GitHub Actions config just to show the failure. Let me know if you want me to remove it from the PR.
> Fix broken unit test in windows

- src/parser.ts
#182 
also fixes FunctionExpression, ArrowFunction, etc.
> Сhange the default value when getting literal value

- src/parser.ts
Fixes #179 based on the comment there.
> Fallback to type.aliasSymbol

- src/__tests__/data/StatelessIntersectionGenericProps.tsx
- src/__tests__/parser.ts
- src/parser.ts
When trying to generate the props for the following structure I was getting nothing
```ts
export type StatelessProps<
T extends React.JSXElementConstructor<any>
> = React.ComponentProps<T> & {
/** myProp description */
myProp: string;
};
/** StatelessIntersectionGenericProps description */
export const StatelessIntersectionGenericProps = <
T extends React.JSXElementConstructor<any>
>(
props: StatelessProps<T>
) => <div />;
```
While other intersections are correctly handled, the generic version would return nothing from `getProperties`. So I just looped through the types in the intersection and call `getProperties` on each.
With my changes my generic components are now successfully generating the props table.
fixes #203
> handle generic intersection

- src/__tests__/data/ComplexGenericUnionIntersection.tsx
- src/__tests__/data/SimpleDiscriminatedUnionIntersection.tsx
- src/__tests__/data/SimpleUnionIntersection.tsx
- src/__tests__/parser.ts
- src/parser.ts
closes #158 
closes #57 
Addresses some of #68 but that issue seems to be more about displaying separate props tables for each set of properties. 
This pull request aims to better `react-docgen-typescript`'s ability to document complex prop types. 
There were a few of these situations fixed in #241 but I missed a few cases.
Intersection + Union
```tsx
type ExampleProps = { foo: string } & ({ bar: string } | { baz: string });
export const Example = (props: ExampleProps) => <div />;
```
*Previous:* Only `foo` received documentation
*Now:* All props receive documentation
Discriminated Intersection + Union
```tsx
type StackProps = { foo: string } & (
| { bar: 'one'; test: number }
| { bar: 'other'; baz: number }
);
export const ExampleProps = (props: StackProps) => <div />
```
*Previous:* …
> handle more complex intersection/union props

- src/__tests__/data/FunctionDeclarationDefaultProps.tsx
- src/__tests__/parser.ts
- src/parser.ts
> fix bug where it wouldn't parse default props on function declaration

- src/__tests__/data/OnlyDefaultExportUnion.tsx
- src/__tests__/parser.ts
- src/parser.ts
> handle only default export with union type

- src/__tests__/data/ExportObject.tsx
- src/__tests__/parser.ts
- src/parser.ts
closes #176
I had to change the following test cases 
https://github.com/styleguidist/react-docgen-typescript/pull/253/files#diff-c4e2044ddda57c0b9b40f972fc77d27eR629
https://github.com/styleguidist/react-docgen-typescript/pull/253/files#diff-c4e2044ddda57c0b9b40f972fc77d27eR643
They were using the name of the file for the name of the component that was already a named export. Since they are named exports and aren't exported as default I think It makes more sense the way it is now. 
We could count how many exports that are, but I think the code in the PR makes more sense
> Handle components exported in an object

- src/__tests__/data/ExportsDefaultInterface.tsx
- src/__tests__/parser.ts
- src/parser.ts
When `export default interface Interface {}` is used the parser currently fails with `Error: Debug Failure. False expression: Should only get Alias here` at Object.resolveAlias [as getAliasedSymbol].
It probably fails for other type only exports as well when they are used as default export. The fix makes sure only actual aliases are passed to `getAliasedSymbol`.
> fix parse error for export default interface

- package-lock.json
- src/__tests__/data/ComponentWithTypeJsDocTag.tsx
- src/__tests__/parser.ts
- src/parser.ts
This commit allows you to use the jsdoc `@type` tag to override the resulting parsed type for a prop.
```ts
export interface IComponentWithTypeJsDocTag {
/**
* sample with custom type
* @type string
*/
sampleTypeFromJSDoc: number;
}
```
This is useful for types that are complicated or too verbose and where you can provide a  simpler type just for the docs.
> feat: allow jsdoc @type to override a prop's type

- README.md
- src/__tests__/parser.ts
- src/parser.ts
Currently this library will only create `enum` docgen types for enums or string unions. [`storybook` is looking to improve the experience](https://github.com/storybookjs/storybook/pull/11106#issuecomment-641764944) here to be more on par with `react-docgen`.
> Add shouldExtractValuesFromUnion option

- package-lock.json
- package.json
- src/__tests__/data/ColumnWithStaticComponents.tsx
- src/__tests__/data/StatelessStaticComponents.tsx
- src/__tests__/parser.ts
- src/parser.ts
Adds the ability to generate docs for static sub-components. Works in both function and class components
```tsx
import * as React from "react";
interface LabelProps {
/** title description */
title: string;
}
/** StatelessStaticComponents.Label description */
const SubComponent = (props: LabelProps) => <div>My Property = {props.title}</div>;
interface StatelessStaticComponentsProps {
/** myProp description */
myProp: string;
}
/** StatelessStaticComponents description */
export const StatelessStaticComponents = (props: StatelessStaticComponentsProps) => (
<div>My Property = {props.myProp}</div>
);
StatelessStaticComponents.Label = SubComponent;
```
The code will construct a `displayName` from the parent component + the sub component's name.
closes #98
> document static sub-components

- src/__tests__/data/ForwardRefDefaultValues.tsx
- src/__tests__/parser.ts
- src/parser.ts
This tries to follow and look inside of `forwardRef` calls when reading out default values from function statements. In addition it will look at the actual source file when doing these default value lookups.
Solves: #254
> Read default prop values from inside a forwardRef

- .travis.yml
- package-lock.json
- package.json
- src/__tests__/data/ComplexGenericUnionIntersectionWithOmit.tsx
- src/__tests__/parser.ts
- src/parser.ts
Commits: 
1. Fix generic union types with an `Omit`. We weren't using the `apparentProps` before and those should be included.
- upgraded TS version to use `as const`
2. Updated and ran prettier on everything (I was having trouble getting a minimal commit diff)
- had to upgrade travis node version for this
> respect base apparentProperties in unions

- src/__tests__/data/JSDocWithParam.tsx
- src/__tests__/parser.ts
- src/parser.ts
Instead of using the full comment for the component we use just the description instead.
closes #133
> use just the description for JSDoc comment instead of full comment

- src/__tests__/data/SeparateDefaultProps.tsx
- src/__tests__/data/SeparateDefaultPropsIndividual.tsx
- src/__tests__/parser.ts
- src/parser.ts
fixes #233 (default props in a variable)
Also fixes issue where you access properties from and object 
```js
const defaults = { id: 123 }
MyComponent.defaultProps = {
id: defaults.id
}
```
> follow default props that are PropertyAccessExpressions

- src/__tests__/data/ForwardRefDefaultExportAtExport.tsx
- src/__tests__/data/FunctionDeclarationAsDefaultExportWithMemo.tsx
- src/__tests__/parser.ts
- src/parser.ts
> fix docgen for default exports wrapped in React.memo or React.forwardRef

- src/__tests__/data/FunctionDeclarationVisibleName.tsx
- src/__tests__/parser.ts
- src/parser.ts
> fix jsDoc visibleName support

- README.md
- src/buildFilter.ts
- src/parser.ts
This PR addresses the following issues without introducing a breaking change. If this PR is accepted #285 can be closed. The naming of this option follows the guidance from @pvasek in [this comment](https://github.com/styleguidist/react-docgen-typescript/pull/285#issuecomment-683404412)
closes #284
closes #236
> add skipChildrenPropWithoutDoc option

- package-lock.json
- package.json
- src/parser.ts
It is proposed that the tagMap object be present in ComponentDoc. This can help developers use any tags to customize or filter the components.
> Add tags to ComponentDoc

- src/__tests__/data/GenericWithExtends.tsx
- src/__tests__/parser.ts
- src/parser.ts
The following pull request modifies how generics are handled by the docgen typing generation, for better support for generic enums when used with storybook.
Consider the following case:
```typescript
function Component<T extends string>(props: { aGenericProp: T }) { return null }
```
The current implementation makes the generated type to be T that storybook resolves to any.
With this change it's checked if the typing is constrained, and if so, obtains the typing from the constraint.
So when it resolves it will see the component definition as:
```typescript
function Component<T extends string>(props: { aGenericProp: string }) { return null }
```
These are the changes that have been made:
+ GenericWithExtends.tsx: Exemplifies a use case and is used by the tests
+ __tests__/parser.ts: This …
> Inferring type from constrained generics

- README.md
- src/__tests__/data/ButtonWithOnClickComponent.tsx
- src/__tests__/data/ColumnWithStaticComponents.tsx
- src/__tests__/data/ComplexGenericUnionIntersection.tsx
- src/__tests__/data/ForwardRefDefaultExportAtExport.tsx
- src/__tests__/data/FunctionDeclarationVisibleName.tsx
- src/__tests__/data/HOCIntersectionProps.tsx
- src/__tests__/data/StatelessIntersectionExternalProps.tsx
- src/__tests__/data/StatelessIntersectionProps.tsx
- src/__tests__/data/StatelessShorthandDefaultProps.tsx
- src/__tests__/data/StatelessStaticComponents.tsx
- src/__tests__/data/StatelessWithDefaultOnlyJsDoc.tsx
- src/__tests__/data/StatelessWithDefaultProps.tsx
- src/__tests__/data/StatelessWithDefaultPropsAsString.tsx
- src/__tests__/data/StatelessWithDefaultPropsTypescript3.tsx
- src/__tests__/data/StatelessWithDestructuredPropsArrow.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
As a developer I would like to have extended information about property type declaration. As some of props could be described as an inheritance of types in `node_modules` it's impossible to opt in such props in `propFilter` function and opt out all the props from `node_modules`.
```tsx
import { FC, PropsWithRef } from 'react';
type HTMLButtonProps = JSX.IntrinsicElements['button'];
type Props = HTMLButtonProps & {
/** onClick event handler */
onClick?: HTMLButtonProps['onClick'];
};
const ButtonWithOnClickComponent: FC<Props> = props => {
return <button {...props} />;
};
export default ButtonWithOnClickComponent;
```
Current version of `react-docgen-typescript` will generate next prop description
```js
{
onClick: {
// ... 
parent: {
fileName: "node_modules/@types/react/index.d.ts",
// ... …
```
> Add more information about parent declaration

- src/__tests__/data/GenericWithExtends.tsx
- src/__tests__/parser.ts
- src/parser.ts
fixed: the following example does not generate an enumerated type
``` ts
export enum Mode {
A,
B,
}
export enum Mode {
A,
B = "b",
}
```
fixed: return the expected enumeration value
```ts
export enum Mode {
A,
B = "b",
}
// old generated 
"type": {
"name": "enum",
"raw": "Mode",
"value": [
{
"value": "Mode.A"
},
{
"value": "\"b\""
}
]
}
// new generated 
"type": {
"name": "enum",
"raw": "Mode",
"value": [
{
"value": "0"
},
{
"value": "\"b\""
}
]
}
```
> improve shouldExtractLiteralValuesFromEnum

- package-lock.json
- src/__tests__/data/ExtractPropTags.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
- zTest.js
@pvasek  sorry for the delay. 
I've updated the PR to 1.21.0, added the union test for the PR and added test functionality to check prop tags in testUtils.ts.
I've also made an additional change in src/parser.ts: 
Only if the added ParserOption shouldIncludePropTagMap is true, instead of jsDocComment.fullComment (default), jsDocComment.description is used as prop description. This will return the plain property description without any tags while tags are served separately. **Default behavior (shouldIncludePropTagMap is false or undefined) is unchanged**. 
I think that would also be an option for default behavior (if so the additional ParserOption would be obsolete). Currently property tags are included in the description as string: 
`
/** prop2 description
* @internal some internal prop
* …
> Added tags for props to serialization (including ParserOption to enable)

- src/__tests__/data/Issue320.tsx
- src/__tests__/parser.ts
- src/parser.ts
Issue/task https://github.com/styleguidist/react-docgen-typescript/issues/320
Changes let developers specify custom component types (like StyledComponent or ForwardRefExoticComponent)
> chore: add an ability to extend component types by option field

- .prettierrc
- src/__tests__/data/RemoveOptionalValuesFromEnum.tsx
- src/__tests__/data/RemoveOptionalValuesFromUnion.tsx
- src/__tests__/parser.ts
- src/parser.ts
Issue: #341 
The `shouldRemoveUndefinedFromOptional` was broken for TypeScript `strict: true` mode.
Will fix https://github.com/storybookjs/storybook/issues/14523
See attached unit tests cc @michelengelen
> Fix shouldRemoveUndefinedFromOptional in TypeScript strict mode

- src/__tests__/data/StatelessDisplayNameDefaultExportDifferentFilename.tsx
- src/__tests__/parser.ts
- src/parser.ts
I noticed that when stateless components are declared as `const Component = (props) => ...` their `displayName` property didn't get parsed correctly when the component is a default export.
This is my first PR to this repo so I hope I did everything right! Let me know if this can be improved in any way. I'm not too hot on the test fixture filename or `displayName` so I'm open to suggestions, I just picked a name that would stress the difference between the file's name and the component's `displayName`.
Thanks for reviewing!
> Parse displayName for stateless components whose name dont match the file name

- src/__tests__/data/ComponentWithImportedDefaultProps.tsx
- src/__tests__/data/const.ts
- src/__tests__/parser.ts
- src/parser.ts
Fixes an error parsing default properties if they are imported from an external module.
> fix: resolving imported defaultProps

- src/parser.ts
The generated ComponentDoc objects do have a filled out `tags` map, so
this patch updates the type.
However, it does not update the `PropItem` type as those tags appear to
always be empty (with tags ending up in the description).
> Fix tags type

- src/__tests__/parser.ts
- src/parser.ts
This is re: https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/51 and https://github.com/storybookjs/storybook/issues/15401 cc @hipstersmoothie @leepowelldev
**tl;dr** This PR would allow consumers who parse components with `react-docgen-typescript` to access the expression for that component.
In Storybook, a component's prop table will break if you set the component's `displayName` to a value that differs from its identifier. For example, let's say that you define a component like this:
```ts
export const Button = (props: ButtonComponentProps) => (
<button>{props.text}</button>
);
Button.displayName = "MyButtonDisplayName";
```
Then [`react-docgen-typescript-plugin`](https://github.com/hipstersmoothie/react-docgen-typescript-plugin) will append code to that module …
> feat: Provide raw expression as part of parser output

- src/__tests__/parser.ts
- src/parser.ts
Resolves #432 cc @joshwooding
This PR adds a property called `rawExpression` to the parsed object when `shouldIncludeExpression` is set, in addition to the existing `expression` property. The two are identical in many cases, but diverge when the exported component has a wrapper such as `React.memo`. Example from the test cases:
```ts
// parsed.expression
function Jumbotron(props: JumbotronProps) {
return <div>Test</div>;
}
// parsed.rawExpression
export default React.memo(Jumbotron);
```
Exporting both will allow developers to extract additional information from the raw expression when necessary.
> feat: Export raw expression when shouldIncludeExpression is set

- src/__tests__/data/StatelessDisplayNameMultipleDisplayNames.tsx
- src/__tests__/data/StatelessDisplayNameMultipleFnsOneDisplayName.tsx
- src/__tests__/parser.ts
- src/parser.ts
Fixes: #395
Fixes: #437
I basically did the fix outlined in #437 by @jesstelford and added some tests.
The tests all seem to fail 😬 
Would love to fix the `displayName` issue, but I'm not sure how to proceed here! Just wanted to put a foot forward. I also would like to add a test specifically about the issue outlined in #395 where the first displayName is applied, even if the function it's applied to is not exported.
> Resolve issue with first displayName always being used

- src/parser.ts
Changed in styled components `6.0.0`. Does not correctly resolve filenames for styled components
> Adds StyledComponents type "IStyledComponents"

- src/__tests__/data/StatelessDisplayNameFolder/Stateless.d.ts
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
There are cases that I have run into where the file being analyzed ends with `.d.ts` and that would inadvertently make the displayName end with an unintended `d`.
For example `List.d.ts` would become `Listd`.
This updates the logic in `getDefaultExportForFile` to split based on the first `.` instead of the last.
> Handle multiple file extensions in `getDefaultExportForFile`
