styleguidist/react-docgen-typescript

- src/docgenConverter.ts
Fixes React Styleguidist 5 compatibility.
> Export displayName

- src/__tests__/data/PureRow.tsx
- src/__tests__/parser.spec.ts
- src/parser.ts
Needed support to parse classes that extends from `React.PureComponent`
Hopefully this PR is OK
https://facebook.github.io/react/docs/react-api.html#react.purecomponent
> PureComponent Support

- src/__tests__/data/AppMenu.tsx
- src/__tests__/data/Row.tsx
- src/__tests__/getFileDocumentation.spec.ts
- src/getFileDocumentation.ts
- src/printUtils.ts
> added test for empty elements, this was failing before last fix

- package.json
- src/__tests__/data/FunctionDeclaration.tsx
- src/__tests__/data/FunctionDeclarationAsDefaultExport.tsx
- src/__tests__/data/FunctionalComponentAsConst.tsx
- src/__tests__/data/FunctionalComponentAsConstAsDefaultExport.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
- yarn.lock
> Fix for default export can have wrong name

- README.md
I was initially stumped by the existing instructions as it did not mention the `propFilter`.
> Improve parserOptions documentation

- examples/react-styleguidist-example/package.json
- examples/react-styleguidist-example/styleguide.config.js
- examples/react-styleguidist-example/yarn.lock
I think it would be nice if we have example of passing parser options in our example project.
> Add example of passing parser options

- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
- src/parser.ts
- tsconfig.json
This PR applies TypeScript strict mode to the code base. It addresses issue #18.
Note that there are some cases where I'm not 100% sure, if this is correct. So please review the PR carefully.
> Apply ts strict mode

- package.json
> point to published type definitions

- src/__tests__/data/ExternalPropsComponentProps.ts
- src/__tests__/data/HOCIntersectionProps.tsx
- src/__tests__/data/StatefulIntersectionExternalProps.tsx
- src/__tests__/data/StatefulIntersectionProps.tsx
- src/__tests__/data/StatelessIntersectionExternalProps.tsx
- src/__tests__/data/StatelessIntersectionProps.tsx
- src/__tests__/data/withHOC.tsx
- src/__tests__/parser.ts
A ton of tests/scenarios for intersection props + HOCs.
Tests for https://github.com/styleguidist/react-docgen-typescript/issues/94
> Test intersection props

- examples/react-styleguidist-example/README.md
- examples/react-styleguidist-example/package.json
- examples/react-styleguidist-example/yarn.lock
- package.json
- src/__tests__/data/ColumnWithLog.tsx
- src/__tests__/parser.ts
- src/parser.ts
fix: #121 The example code don't work
fix: #120 programProvider is not a function
fix: #92 console.log causes TypeError in parser
> Various fixes

- package-lock.json
- src/parser.ts
- tsconfig.json
Please merge #124 before this one.
Closes #123.
> Fix parse with program provider warning

- src/parser.ts
> fix: better error message for non existing custom tsconfig

- src/__tests__/data/ColumnWithPropsWithExternalType.MyExternalType.tsx
- src/__tests__/data/ColumnWithPropsWithExternalType.tsx
- src/__tests__/parser.ts
Added unit test for bug #177. Props with property with external type.
> feat: props with property with external type

- README.md
- package.json
- src/__tests__/data/Issue188.tsx
- src/__tests__/parser.ts
- src/__tests__/testUtils.ts
Attempt to fix issue #185. Added test for issue #188.
> fix: npmjs link fixed, issue test added

- README.md
> fix: typo in propFilter example

- src/parser.ts
Fixes #213 
I'm afraid I cannot provide a unit test for this. Your codebase is simply to complex for me to identify, what the actual underlying issue is.
However, I'm open to share as much information as needed.
> fix: cannot read property 'filter' of undefined

- src/__tests__/data/StatelessWithDefaultOnlyJsDoc.tsx
- src/__tests__/parser.ts
- src/parser.ts
> Fix @default jsdoc annotation with no description being ignored

- package-lock.json
- package.json
> add missing peer dep on typescript

- README.md
- src/parser.ts
Tried to add tests for this but I couldn't the code to add " | undefined" in this project. Loaded it into my storybook and verified that it works though
closes #81
> Add `shouldRemoveUndefinedFromOptional` option

- README.md
> clear up docs around "propFilter"

- src/__tests__/data/ForwardRefDefaultExport.tsx
- src/__tests__/parser.ts
- src/parser.ts
> fix default export w/forwardRef

- README.md
> add public API docs

- src/parser.ts
https://github.com/styleguidist/react-docgen-typescript/issues/276
> Fix issues#276 "Cannot read property 'getSourceFile' of undefined"

- src/parser.ts
> fix: 🐛 fixed declarations.length is undefined

- src/parser.ts
> Export defaultOptions from parser

- src/parser.ts
related issue: https://github.com/styleguidist/react-docgen-typescript/issues/301
@pvasek
> fix: fix when initializer is undefined

- src/__tests__/data/RemoveOptionalValuesFromEnum.tsx
- src/__tests__/parser.ts
- src/parser.ts
Hi, I think we can get union type with comment info ,here 's my pull request.  Looking forward to your reply !😄
> feat: get comment info for union type

- package-lock.json
- src/__tests__/parser.ts
- src/parser.ts
There was a regression issue in #411 and only a single test was setup to run. 
Both of these issues went unnoticed by me 😐
Also the `package-lock.json` was regenerated with the newer npm version.
> fix: the merging of PR #411 introduced a regression error

- src/parser.ts
> fix: declaration array can be undefined
